# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#

[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.2.0"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "1.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.1.1"

[prune]
  go-tests = true
  unused-packages = true
